AccessModifierIndentation:
  Enabled: false

AndOr:
  Enabled: false

Documentation:
  Enabled: false

EndAlignment:
  Enabled: false

IndentationWidth:
  Enabled: false

MethodDefParentheses:
  Enabled: false

SingleLineBlockParams:
  Enabled: false
