Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
