Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - bin/lovely-rufus

Style/Not:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SpaceAfterNot:
  Enabled: false
