AndOr:
  Enabled: false

Documentation:
  Enabled: false

FileName:
  Exclude:
    - bin/lovely-rufus

Next:
  Exclude:
    - lib/lovely_rufus/hangout_wrapper.rb

SingleLineBlockParams:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false
