Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - bin/lovely-rufus

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false
