AndOr:
  Enabled: false

Documentation:
  Enabled: false

FileName:
  Exclude:
    - bin/lovely-rufus

MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

SingleLineBlockParams:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false
