Layout/SpaceAfterNot:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - bin/lovely-rufus

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Not:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false
