DuplicateMethodCall:
  exclude:
  - LovelyRufus::BasicWrapper#call
  - LovelyRufus::HangoutWrapper#rewrapped

FeatureEnvy:
  exclude:
  - LovelyRufus::BasicWrapper#call
  - LovelyRufus::HangoutWrapper#hangout_line
  - LovelyRufus::OneLetterGluer#call
  - LovelyRufus::QuoteStripper#quote

IrresponsibleModule:
  enabled: false

NestedIterators:
  max_allowed_nesting: 2

UncommunicativeVariableName:
  exclude:
  - LovelyRufus::HangoutWrapper#hangout_line

UnusedParameters:
  exclude:
  - LovelyRufus::Layer#call
