DuplicateMethodCall:
  exclude:
    - LovelyRufus::BasicWrapper#call
    - LovelyRufus::HangoutWrapper#rewrapped

FeatureEnvy:
  exclude:
    - LovelyRufus::BasicWrapper#call
    - LovelyRufus::HangoutWrapper#hangout_line
    - LovelyRufus::OneLetterGluer#call
    - LovelyRufus::QuoteStripper#quote

IrresponsibleModule:
  enabled: false

NestedIterators:
  exclude:
    - LovelyRufus#initialize

UncommunicativeVariableName:
  exclude:
    - LovelyRufus::HangoutWrapper#hangout_line
