IrresponsibleModule:
  enabled: false

NestedIterators:
  max_allowed_nesting: 2

UncommunicativeVariableName:
  exclude:
  - LovelyRufus::HangoutWrapper#hangout_line

# side-step Reek treating all kwargs as unused:
# https://github.com/troessner/reek/pull/237
UnusedParameters:
  exclude:
  - LovelyRufus::BasicWrapper#initialize
  - LovelyRufus::CLIWrapper#initialize
  - LovelyRufus::HangoutWrapper#initialize
  - LovelyRufus::OneLetterGluer#initialize
  - LovelyRufus::TextWrapper#initialize
  - LovelyRufus::TextWrapper#self.wrap
