DuplicateMethodCall:
  exclude:
    - LovelyRufus::BasicWrapper#call

FeatureEnvy:
  exclude:
    - LovelyRufus::BasicWrapper#call
    - LovelyRufus::OneLetterGluer#call
    - LovelyRufus::QuoteStripper#quote
    # https://github.com/troessner/reek/issues/53
    - LovelyRufus::HangoutWrapper::HangoutFinder

IrresponsibleModule:
  enabled: false

UncommunicativeVariableName:
  exclude:
    - LovelyRufus::HangoutWrapper#hangout_line

UtilityFunction:
  exclude:
    # https://github.com/troessner/reek/issues/27
    - LovelyRufus::HangoutWrapper::HangoutFinder
