DuplicateMethodCall:
  exclude:
  - LovelyRufus::BasicWrapper#call
  - LovelyRufus::HangoutWrapper#rewrapped

IrresponsibleModule:
  enabled: false

NestedIterators:
  max_allowed_nesting: 2

UncommunicativeVariableName:
  exclude:
  - LovelyRufus::HangoutWrapper#hangout_line

UnusedParameters:
  exclude:
  - LovelyRufus::Layer#call
  - LovelyRufus::OneLetterGluer#call
